[package]
name = "findoor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
structopt = "0.3.26"
tiny-keccak = {version = "2.0.2", features=["keccak"]}
